version: '3.4'

services:
  generador:
    image: ${DOCKER_REGISTRY-}generador
    build:
      context: .
      dockerfile: Generador/Dockerfile    
    environment:
        Generador__Name: A0
        Generador__Interval: 5000
    depends_on:
      - 'rabbitmq'
    networks:
      - sensor_net
 
  generadorPeriode:
    image: ${DOCKER_REGISTRY-}generador
    build:
      context: .
      dockerfile: Generador/Dockerfile    
    environment:
        Generador__Name: B0
        Generador__Interval: 30000
    depends_on:
      - 'rabbitmq'
    networks:
      - sensor_net

  generadorPressioAtmosferica:
    image: ${DOCKER_REGISTRY-}generador
    build:
      context: .
      dockerfile: Generador/Dockerfile    
    environment:
        Generador__Name: C0
        Generador__Interval: 30000
    depends_on:
      - 'rabbitmq'
    networks:
      - sensor_net

 
  gestordades:
    image: ${DOCKER_REGISTRY-}gestordades
    build:
      context: .
      dockerfile: GestorDades/Dockerfile
    ports:
        - 5098:5098
    depends_on:
      - 'rabbitmq'
    networks:
      - sensor_net

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
        - 80:80
        - 443:443
    networks:
      - sensor_net 


  tractament:    
    image: ${DOCKER_REGISTRY-}tractament    
    depends_on:
      - 'rabbitmq'
    networks:
        - sensor_net
    environment:
         PYTHONUNBUFFERED: 1
         RabbitMQCalculDades__User: guest
         RabbitMQCalculDades__Password: guest

  rabbitmq:    
    image: rabbitmq    
    ports:        
        - 5672:5672
        - 15672:15672
    networks:
        - sensor_net

networks:
  sensor_net:
    name: sensor_net