version: '3.4'

services:
  generador:
    image: ${DOCKER_REGISTRY-}generador
    build:
      context: .
      dockerfile: Generador/Dockerfile    
    environment:
        Generador__Name: PIE1_RES
    depends_on:
      - 'rabbitmq'
    networks:
      - sensor_net
 
  generadorPeriode:
    image: ${DOCKER_REGISTRY-}generador
    build:
      context: .
      dockerfile: Generador/Dockerfile    
    environment:
        Generador__Name: PIE1_PER
    depends_on:
      - 'rabbitmq'
    networks:
      - sensor_net

  generadorPressioAtmosferica:
    image: ${DOCKER_REGISTRY-}generador
    build:
      context: .
      dockerfile: Generador/Dockerfile    
    environment:
        Generador__Name: METEO_PRE
    depends_on:
      - 'rabbitmq'
    networks:
      - sensor_net

 
  magatzem:
    image: ${DOCKER_REGISTRY-}magatzem
    build:
      context: .
      dockerfile: Magatzem/Dockerfile
    ports:
        - 5098:5098
    depends_on:
      - 'rabbitmq'
    networks:
      - sensor_net

  tractament:    
    image: ${DOCKER_REGISTRY-}tractament    
    depends_on:
      - 'rabbitmq'
    networks:
        - sensor_net
    environment:
        - PYTHONUNBUFFERED=1

  rabbitmq:    
    image: rabbitmq    
    ports:        
        - 5672:5672
        - 15672:15672
    networks:
        - sensor_net

networks:
  sensor_net:
    name: sensor_net