apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfg
spec:
  selector:
    matchLabels:
      app: gestordades
  replicas: 1        
  template:
    metadata:
      labels:
        app: gestordades
    spec:
      containers:
      - name: gestordades
        image: gestordades
        imagePullPolicy: IfNotPresent
        env:
          - name: RabbitMQDadesGenerades__User
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user  
                key: username        
          - name: RabbitMQDadesGenerades__Password
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
        resources:
          limits:
            memory: "128Mi"   
            cpu: "200m"         
          requests:
            memory: "8Mi"
            cpu: "100m"
        livenessProbe:
          grpc:
            port: 5098
          initialDelaySeconds: 1
        readinessProbe:      
          grpc:
            port: 5098
          initialDelaySeconds: 1

