apiVersion: apps/v1
kind: Deployment
metadata:
  name: generador-res
  labels:
    app: generador
spec:
  selector:
    matchLabels:
      app: generador
  template:
    metadata:
      labels:
        app: generador
    spec:
      containers:
      - name: generador
        image: generador
        imagePullPolicy: IfNotPresent
        env:
          - name: Generador__Interval
            value: "0"
          - name: Generador__Name
            value: PIE_RES
          - name: RabbitMQDadesGenerades__User
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user  
                key: username        
          - name: RabbitMQDadesGenerades__Password
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
        resources:       
          requests:
            memory: "8Mi"
            cpu: "100m"
        livenessProbe:
          grpc:
            port: 5098
          initialDelaySeconds: 5
        readinessProbe:      
          grpc:
            port: 5098
          initialDelaySeconds: 5          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generador-per
spec:
  selector:
    matchLabels:
      app: generador
  template:
    metadata:
      labels:
        app: generador
    spec:
      containers:
      - name: generador
        image: generador
        imagePullPolicy: IfNotPresent
        env:
          - name: Generador__Interval
            value: "0"
          - name: Generador__Name
            value: PIE_PER
          - name: RabbitMQDadesGenerades__User
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user  
                key: username        
          - name: RabbitMQDadesGenerades__Password
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
        resources:
          limits:
            memory: "512Mi"   
            cpu: "1000m"         
          requests:
            memory: "8Mi"
            cpu: "100m"
        livenessProbe:
          grpc:
            port: 5098
          initialDelaySeconds: 5
        readinessProbe:      
          grpc:
            port: 5098
          initialDelaySeconds: 5  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generador-pre
spec:
  selector:
    matchLabels:
      app: generador
  template:
    metadata:
      labels:
        app: generador
    spec:
      containers:      
      - name: generador
        image: generador
        imagePullPolicy: IfNotPresent
        env:
          - name: Generador__Interval
            value: "0"
          - name: Generador__Name
            value: METEO_PRE
          - name: RabbitMQDadesGenerades__User
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user  
                key: username        
          - name: RabbitMQDadesGenerades__Password
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
        resources:
          limits:
            memory: "512Mi"   
            cpu: "1000m"         
          requests:
            memory: "8Mi"
            cpu: "100m"
        livenessProbe:
          grpc:
            port: 5098
          initialDelaySeconds: 5
        readinessProbe:      
          grpc:
            port: 5098
          initialDelaySeconds: 5            