apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestordades
  labels:
    app: gestordades
spec:
  selector:
    matchLabels:
      app: gestordades
  replicas: 1
  template:
    metadata:
      labels:
        app: gestordades
    spec:
      containers:
      - name: gestordades
        image: gestordades
        imagePullPolicy: IfNotPresent
        env:
          - name: RabbitMQDadesGenerades__User
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user  
                key: username        
          - name: RabbitMQDadesGenerades__Password
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
          - name: RabbitMQDadesCalculades__User
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user  
                key: username        
          - name: RabbitMQDadesCalculades__Password
            valueFrom:  
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
        resources:
          limits:
            memory: "128Mi"   
            cpu: "1000m"         
          requests:
            memory: "8Mi"
            cpu: "100m"
        ports:
          - name: grpc
            containerPort: 5098
        livenessProbe:
          grpc:
            port: 5098
          initialDelaySeconds: 1
        readinessProbe:      
          grpc:
            port: 5098
          initialDelaySeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gestordades-rpc
spec:
  selector:
    app: gestordades
  ports:
  - port: 5098
    targetPort: grpc


