apiVersion: v1
kind: Pod
metadata:
  name: generador-res
spec:
  containers:
  - name: generador
    image: generador
    imagePullPolicy: IfNotPresent
    env:
      - name: Generador__Name
        value: PIE_RES
      - name: RabbitMQDadesGenerades__User
        valueFrom:  
          secretKeyRef:
            name: rabbitmq-default-user  
            key: username        
      - name: RabbitMQDadesGenerades__Password
        valueFrom:  
          secretKeyRef:
            name: rabbitmq-default-user
            key: password
    resources:
      limits:
        memory: "32Mi"   
        cpu: "1000m"         
      requests:
        memory: "8Mi"
        cpu: "100m"
    livenessProbe:
      grpc:
        port: 5098
      initialDelaySeconds: 5
    readinessProbe:      
      grpc:
        port: 5098
      initialDelaySeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: generador-per
spec:
  containers:
  - name: generador
    image: generador
    imagePullPolicy: IfNotPresent
    env:
      - name: Generador__Name
        value: PIE_PER
      - name: RabbitMQDadesGenerades__User
        valueFrom:  
          secretKeyRef:
            name: rabbitmq-default-user  
            key: username        
      - name: RabbitMQDadesGenerades__Password
        valueFrom:  
          secretKeyRef:
            name: rabbitmq-default-user
            key: password
    resources:
      limits:
        memory: "128Mi"   
        cpu: "1000m"         
      requests:
        memory: "8Mi"
        cpu: "100m"
    livenessProbe:
      grpc:
        port: 5098
      initialDelaySeconds: 5
    readinessProbe:      
      grpc:
        port: 5098
      initialDelaySeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: generador-pre
spec:
  containers:
  - name: generador
    image: generador
    imagePullPolicy: IfNotPresent
    env:
      - name: Generador__Name
        value: METEO_PRE
      - name: RabbitMQDadesGenerades__User
        valueFrom:  
          secretKeyRef:
            name: rabbitmq-default-user  
            key: username        
      - name: RabbitMQDadesGenerades__Password
        valueFrom:  
          secretKeyRef:
            name: rabbitmq-default-user
            key: password
    resources:
      limits:
        memory: "32Mi"   
        cpu: "1000m"         
      requests:
        memory: "8Mi"
        cpu: "100m"
    livenessProbe:
      grpc:
        port: 5098
      initialDelaySeconds: 5
    readinessProbe:      
      grpc:
        port: 5098
      initialDelaySeconds: 5
