apiVersion: apps/v1
kind: Deployment
metadata:
  name: tractament
spec:
  selector:
    matchLabels:
      app: tractament
  template:
    metadata:
      labels:
        app: tractament
    spec:
      containers:
      - name: tractament
        image: tractament
        imagePullPolicy: IfNotPresent        
        env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: GRPCValors__Host
              value: "gestordades-rpc"
            - name: RabbitMQCalculDades__User            
              valueFrom:  
                secretKeyRef:
                  name: rabbitmq-default-user  
                  key: username        
            - name: RabbitMQCalculDades__Password
              valueFrom:  
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"        
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tractament
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tractament
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40