# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: missatges.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmissatges.proto\x12\x0bTFGProtocol\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n\x0c\x44\x61\x64\x61Generada\x12\r\n\x05valor\x18\x01 \x01(\x01\x12\x31\n\rdataGeneracio\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"P\n\x0c\x44\x61\x64\x61Tractada\x12\r\n\x05valor\x18\x01 \x01(\t\x12\x31\n\rdataGeneracio\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"j\n\rDatesConsulta\x12-\n\tdataInici\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x06\x64\x61taFi\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"9\n\rRespostaDades\x12(\n\x05\x44\x61\x64\x65s\x18\x01 \x03(\x0b\x32\x19.TFGProtocol.DadaTractadaB\x0f\xaa\x02\x0cTFG.Protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'missatges_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014TFG.Protobuf'
  _globals['_DADAGENERADA']._serialized_start=65
  _globals['_DADAGENERADA']._serialized_end=145
  _globals['_DADATRACTADA']._serialized_start=147
  _globals['_DADATRACTADA']._serialized_end=227
  _globals['_DATESCONSULTA']._serialized_start=229
  _globals['_DATESCONSULTA']._serialized_end=335
  _globals['_RESPOSTADADES']._serialized_start=337
  _globals['_RESPOSTADADES']._serialized_end=394
# @@protoc_insertion_point(module_scope)
