# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: missatges.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmissatges.proto\x12\x0bTFGProtocol\"0\n\x0c\x44\x61\x64\x61Generada\x12\r\n\x05valor\x18\x01 \x01(\x01\x12\x11\n\tnomSensor\x18\x02 \x01(\t\"\x83\x01\n\nCalculDada\x12\x18\n\x10variableCalcular\x18\x01 \x01(\t\x12\x16\n\x0evariableRebuda\x18\x02 \x01(\t\x12\x12\n\nvalorRebut\x18\x03 \x01(\x01\x12\x16\n\x0etimestampRebut\x18\x04 \x01(\r\x12\x17\n\x0ftimestampAltres\x18\x05 \x01(\r\"F\n\rDadaCalculada\x12\x13\n\x0bnomVariable\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\r\"*\n\x04\x44\x61\x64\x61\x12\x13\n\x0bnomVariable\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\x01\"$\n\rConsultaDades\x12\x13\n\x0bnomVariable\x18\x01 \x03(\t\"1\n\rRespostaDades\x12 \n\x05\x44\x61\x64\x65s\x18\x01 \x03(\x0b\x32\x11.TFGProtocol.DadaB\x0f\xaa\x02\x0cTFG.Protobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'missatges_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014TFG.Protobuf'
  _DADAGENERADA._serialized_start=32
  _DADAGENERADA._serialized_end=80
  _CALCULDADA._serialized_start=83
  _CALCULDADA._serialized_end=214
  _DADACALCULADA._serialized_start=216
  _DADACALCULADA._serialized_end=286
  _DADA._serialized_start=288
  _DADA._serialized_end=330
  _CONSULTADADES._serialized_start=332
  _CONSULTADADES._serialized_end=368
  _RESPOSTADADES._serialized_start=370
  _RESPOSTADADES._serialized_end=419
# @@protoc_insertion_point(module_scope)
