// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Missatges.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TFG.Protobuf {

  /// <summary>Holder for reflection information generated from Missatges.proto</summary>
  public static partial class MissatgesReflection {

    #region Descriptor
    /// <summary>File descriptor for Missatges.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MissatgesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9NaXNzYXRnZXMucHJvdG8SC1RGR1Byb3RvY29sGh9nb29nbGUvcHJvdG9i",
            "dWYvdGltZXN0YW1wLnByb3RvIlAKDERhZGFHZW5lcmFkYRINCgV2YWxvchgB",
            "IAEoARIxCg1kYXRhR2VuZXJhY2lvGAIgASgLMhouZ29vZ2xlLnByb3RvYnVm",
            "LlRpbWVzdGFtcCJQCgxEYWRhVHJhY3RhZGESDQoFdmFsb3IYASABKAkSMQoN",
            "ZGF0YUdlbmVyYWNpbxgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3Rh",
            "bXAiagoNRGF0ZXNDb25zdWx0YRItCglkYXRhSW5pY2kYASABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wEioKBmRhdGFGaRgCIAEoCzIaLmdvb2ds",
            "ZS5wcm90b2J1Zi5UaW1lc3RhbXAiOQoNUmVzcG9zdGFEYWRlcxIoCgVEYWRl",
            "cxgBIAMoCzIZLlRGR1Byb3RvY29sLkRhZGFUcmFjdGFkYUIPqgIMVEZHLlBy",
            "b3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.DadaGenerada), global::TFG.Protobuf.DadaGenerada.Parser, new[]{ "Valor", "DataGeneracio" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.DadaTractada), global::TFG.Protobuf.DadaTractada.Parser, new[]{ "Valor", "DataGeneracio" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.DatesConsulta), global::TFG.Protobuf.DatesConsulta.Parser, new[]{ "DataInici", "DataFi" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.RespostaDades), global::TFG.Protobuf.RespostaDades.Parser, new[]{ "Dades" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DadaGenerada : pb::IMessage<DadaGenerada>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DadaGenerada> _parser = new pb::MessageParser<DadaGenerada>(() => new DadaGenerada());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DadaGenerada> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaGenerada() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaGenerada(DadaGenerada other) : this() {
      valor_ = other.valor_;
      dataGeneracio_ = other.dataGeneracio_ != null ? other.dataGeneracio_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaGenerada Clone() {
      return new DadaGenerada(this);
    }

    /// <summary>Field number for the "valor" field.</summary>
    public const int ValorFieldNumber = 1;
    private double valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    /// <summary>Field number for the "dataGeneracio" field.</summary>
    public const int DataGeneracioFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dataGeneracio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DataGeneracio {
      get { return dataGeneracio_; }
      set {
        dataGeneracio_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DadaGenerada);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DadaGenerada other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Valor, other.Valor)) return false;
      if (!object.Equals(DataGeneracio, other.DataGeneracio)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Valor != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Valor);
      if (dataGeneracio_ != null) hash ^= DataGeneracio.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Valor != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Valor);
      }
      if (dataGeneracio_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DataGeneracio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Valor != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Valor);
      }
      if (dataGeneracio_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DataGeneracio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Valor != 0D) {
        size += 1 + 8;
      }
      if (dataGeneracio_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataGeneracio);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DadaGenerada other) {
      if (other == null) {
        return;
      }
      if (other.Valor != 0D) {
        Valor = other.Valor;
      }
      if (other.dataGeneracio_ != null) {
        if (dataGeneracio_ == null) {
          DataGeneracio = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DataGeneracio.MergeFrom(other.DataGeneracio);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Valor = input.ReadDouble();
            break;
          }
          case 18: {
            if (dataGeneracio_ == null) {
              DataGeneracio = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataGeneracio);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Valor = input.ReadDouble();
            break;
          }
          case 18: {
            if (dataGeneracio_ == null) {
              DataGeneracio = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataGeneracio);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DadaTractada : pb::IMessage<DadaTractada>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DadaTractada> _parser = new pb::MessageParser<DadaTractada>(() => new DadaTractada());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DadaTractada> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaTractada() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaTractada(DadaTractada other) : this() {
      valor_ = other.valor_;
      dataGeneracio_ = other.dataGeneracio_ != null ? other.dataGeneracio_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaTractada Clone() {
      return new DadaTractada(this);
    }

    /// <summary>Field number for the "valor" field.</summary>
    public const int ValorFieldNumber = 1;
    private string valor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Valor {
      get { return valor_; }
      set {
        valor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dataGeneracio" field.</summary>
    public const int DataGeneracioFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dataGeneracio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DataGeneracio {
      get { return dataGeneracio_; }
      set {
        dataGeneracio_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DadaTractada);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DadaTractada other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Valor != other.Valor) return false;
      if (!object.Equals(DataGeneracio, other.DataGeneracio)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Valor.Length != 0) hash ^= Valor.GetHashCode();
      if (dataGeneracio_ != null) hash ^= DataGeneracio.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Valor.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Valor);
      }
      if (dataGeneracio_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DataGeneracio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Valor.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Valor);
      }
      if (dataGeneracio_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DataGeneracio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Valor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Valor);
      }
      if (dataGeneracio_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataGeneracio);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DadaTractada other) {
      if (other == null) {
        return;
      }
      if (other.Valor.Length != 0) {
        Valor = other.Valor;
      }
      if (other.dataGeneracio_ != null) {
        if (dataGeneracio_ == null) {
          DataGeneracio = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DataGeneracio.MergeFrom(other.DataGeneracio);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Valor = input.ReadString();
            break;
          }
          case 18: {
            if (dataGeneracio_ == null) {
              DataGeneracio = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataGeneracio);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Valor = input.ReadString();
            break;
          }
          case 18: {
            if (dataGeneracio_ == null) {
              DataGeneracio = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataGeneracio);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DatesConsulta : pb::IMessage<DatesConsulta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DatesConsulta> _parser = new pb::MessageParser<DatesConsulta>(() => new DatesConsulta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DatesConsulta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatesConsulta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatesConsulta(DatesConsulta other) : this() {
      dataInici_ = other.dataInici_ != null ? other.dataInici_.Clone() : null;
      dataFi_ = other.dataFi_ != null ? other.dataFi_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatesConsulta Clone() {
      return new DatesConsulta(this);
    }

    /// <summary>Field number for the "dataInici" field.</summary>
    public const int DataIniciFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dataInici_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DataInici {
      get { return dataInici_; }
      set {
        dataInici_ = value;
      }
    }

    /// <summary>Field number for the "dataFi" field.</summary>
    public const int DataFiFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dataFi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DataFi {
      get { return dataFi_; }
      set {
        dataFi_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DatesConsulta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DatesConsulta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(DataInici, other.DataInici)) return false;
      if (!object.Equals(DataFi, other.DataFi)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (dataInici_ != null) hash ^= DataInici.GetHashCode();
      if (dataFi_ != null) hash ^= DataFi.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (dataInici_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DataInici);
      }
      if (dataFi_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DataFi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (dataInici_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DataInici);
      }
      if (dataFi_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DataFi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (dataInici_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataInici);
      }
      if (dataFi_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataFi);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DatesConsulta other) {
      if (other == null) {
        return;
      }
      if (other.dataInici_ != null) {
        if (dataInici_ == null) {
          DataInici = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DataInici.MergeFrom(other.DataInici);
      }
      if (other.dataFi_ != null) {
        if (dataFi_ == null) {
          DataFi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DataFi.MergeFrom(other.DataFi);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (dataInici_ == null) {
              DataInici = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataInici);
            break;
          }
          case 18: {
            if (dataFi_ == null) {
              DataFi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataFi);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (dataInici_ == null) {
              DataInici = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataInici);
            break;
          }
          case 18: {
            if (dataFi_ == null) {
              DataFi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataFi);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RespostaDades : pb::IMessage<RespostaDades>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespostaDades> _parser = new pb::MessageParser<RespostaDades>(() => new RespostaDades());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespostaDades> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespostaDades() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespostaDades(RespostaDades other) : this() {
      dades_ = other.dades_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespostaDades Clone() {
      return new RespostaDades(this);
    }

    /// <summary>Field number for the "Dades" field.</summary>
    public const int DadesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::TFG.Protobuf.DadaTractada> _repeated_dades_codec
        = pb::FieldCodec.ForMessage(10, global::TFG.Protobuf.DadaTractada.Parser);
    private readonly pbc::RepeatedField<global::TFG.Protobuf.DadaTractada> dades_ = new pbc::RepeatedField<global::TFG.Protobuf.DadaTractada>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TFG.Protobuf.DadaTractada> Dades {
      get { return dades_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespostaDades);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespostaDades other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dades_.Equals(other.dades_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dades_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dades_.WriteTo(output, _repeated_dades_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dades_.WriteTo(ref output, _repeated_dades_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += dades_.CalculateSize(_repeated_dades_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespostaDades other) {
      if (other == null) {
        return;
      }
      dades_.Add(other.dades_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dades_.AddEntriesFrom(input, _repeated_dades_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dades_.AddEntriesFrom(ref input, _repeated_dades_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
