// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: missatges.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TFG.Protobuf {

  /// <summary>Holder for reflection information generated from missatges.proto</summary>
  public static partial class MissatgesReflection {

    #region Descriptor
    /// <summary>File descriptor for missatges.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MissatgesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9taXNzYXRnZXMucHJvdG8SC1RGR1Byb3RvY29sGh9nb29nbGUvcHJvdG9i",
            "dWYvdGltZXN0YW1wLnByb3RvIjAKDERhZGFHZW5lcmFkYRINCgV2YWxvchgB",
            "IAEoARIRCglub21TZW5zb3IYAiABKAkigwEKCkNhbGN1bERhZGESGAoQdmFy",
            "aWFibGVDYWxjdWxhchgBIAEoCRIWCg52YXJpYWJsZVJlYnVkYRgCIAEoCRIS",
            "Cgp2YWxvclJlYnV0GAMgASgBEhYKDnRpbWVTdGFtcFJlYnV0GAQgASgNEhcK",
            "D3RpbWVTdGFtcEFjdHVhbBgFIAEoDSIVCgREYWRhEg0KBXZhbG9yGAEgASgB",
            "ImoKDURhdGVzQ29uc3VsdGESLQoJZGF0YUluaWNpGAEgASgLMhouZ29vZ2xl",
            "LnByb3RvYnVmLlRpbWVzdGFtcBIqCgZkYXRhRmkYAiABKAsyGi5nb29nbGUu",
            "cHJvdG9idWYuVGltZXN0YW1wIjEKDVJlc3Bvc3RhRGFkZXMSIAoFRGFkZXMY",
            "ASADKAsyES5URkdQcm90b2NvbC5EYWRhQg+qAgxURkcuUHJvdG9idWZiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.DadaGenerada), global::TFG.Protobuf.DadaGenerada.Parser, new[]{ "Valor", "NomSensor" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.CalculDada), global::TFG.Protobuf.CalculDada.Parser, new[]{ "VariableCalcular", "VariableRebuda", "ValorRebut", "TimeStampRebut", "TimeStampActual" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.Dada), global::TFG.Protobuf.Dada.Parser, new[]{ "Valor" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.DatesConsulta), global::TFG.Protobuf.DatesConsulta.Parser, new[]{ "DataInici", "DataFi" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TFG.Protobuf.RespostaDades), global::TFG.Protobuf.RespostaDades.Parser, new[]{ "Dades" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DadaGenerada : pb::IMessage<DadaGenerada>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DadaGenerada> _parser = new pb::MessageParser<DadaGenerada>(() => new DadaGenerada());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DadaGenerada> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaGenerada() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaGenerada(DadaGenerada other) : this() {
      valor_ = other.valor_;
      nomSensor_ = other.nomSensor_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DadaGenerada Clone() {
      return new DadaGenerada(this);
    }

    /// <summary>Field number for the "valor" field.</summary>
    public const int ValorFieldNumber = 1;
    private double valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    /// <summary>Field number for the "nomSensor" field.</summary>
    public const int NomSensorFieldNumber = 2;
    private string nomSensor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NomSensor {
      get { return nomSensor_; }
      set {
        nomSensor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DadaGenerada);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DadaGenerada other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Valor, other.Valor)) return false;
      if (NomSensor != other.NomSensor) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Valor != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Valor);
      if (NomSensor.Length != 0) hash ^= NomSensor.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Valor != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Valor);
      }
      if (NomSensor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NomSensor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Valor != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Valor);
      }
      if (NomSensor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NomSensor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Valor != 0D) {
        size += 1 + 8;
      }
      if (NomSensor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NomSensor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DadaGenerada other) {
      if (other == null) {
        return;
      }
      if (other.Valor != 0D) {
        Valor = other.Valor;
      }
      if (other.NomSensor.Length != 0) {
        NomSensor = other.NomSensor;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Valor = input.ReadDouble();
            break;
          }
          case 18: {
            NomSensor = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Valor = input.ReadDouble();
            break;
          }
          case 18: {
            NomSensor = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CalculDada : pb::IMessage<CalculDada>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CalculDada> _parser = new pb::MessageParser<CalculDada>(() => new CalculDada());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CalculDada> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalculDada() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalculDada(CalculDada other) : this() {
      variableCalcular_ = other.variableCalcular_;
      variableRebuda_ = other.variableRebuda_;
      valorRebut_ = other.valorRebut_;
      timeStampRebut_ = other.timeStampRebut_;
      timeStampActual_ = other.timeStampActual_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalculDada Clone() {
      return new CalculDada(this);
    }

    /// <summary>Field number for the "variableCalcular" field.</summary>
    public const int VariableCalcularFieldNumber = 1;
    private string variableCalcular_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VariableCalcular {
      get { return variableCalcular_; }
      set {
        variableCalcular_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "variableRebuda" field.</summary>
    public const int VariableRebudaFieldNumber = 2;
    private string variableRebuda_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VariableRebuda {
      get { return variableRebuda_; }
      set {
        variableRebuda_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "valorRebut" field.</summary>
    public const int ValorRebutFieldNumber = 3;
    private double valorRebut_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double ValorRebut {
      get { return valorRebut_; }
      set {
        valorRebut_ = value;
      }
    }

    /// <summary>Field number for the "timeStampRebut" field.</summary>
    public const int TimeStampRebutFieldNumber = 4;
    private uint timeStampRebut_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimeStampRebut {
      get { return timeStampRebut_; }
      set {
        timeStampRebut_ = value;
      }
    }

    /// <summary>Field number for the "timeStampActual" field.</summary>
    public const int TimeStampActualFieldNumber = 5;
    private uint timeStampActual_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimeStampActual {
      get { return timeStampActual_; }
      set {
        timeStampActual_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CalculDada);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CalculDada other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VariableCalcular != other.VariableCalcular) return false;
      if (VariableRebuda != other.VariableRebuda) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ValorRebut, other.ValorRebut)) return false;
      if (TimeStampRebut != other.TimeStampRebut) return false;
      if (TimeStampActual != other.TimeStampActual) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VariableCalcular.Length != 0) hash ^= VariableCalcular.GetHashCode();
      if (VariableRebuda.Length != 0) hash ^= VariableRebuda.GetHashCode();
      if (ValorRebut != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ValorRebut);
      if (TimeStampRebut != 0) hash ^= TimeStampRebut.GetHashCode();
      if (TimeStampActual != 0) hash ^= TimeStampActual.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VariableCalcular.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VariableCalcular);
      }
      if (VariableRebuda.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(VariableRebuda);
      }
      if (ValorRebut != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(ValorRebut);
      }
      if (TimeStampRebut != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(TimeStampRebut);
      }
      if (TimeStampActual != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(TimeStampActual);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VariableCalcular.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VariableCalcular);
      }
      if (VariableRebuda.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(VariableRebuda);
      }
      if (ValorRebut != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(ValorRebut);
      }
      if (TimeStampRebut != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(TimeStampRebut);
      }
      if (TimeStampActual != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(TimeStampActual);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VariableCalcular.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VariableCalcular);
      }
      if (VariableRebuda.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VariableRebuda);
      }
      if (ValorRebut != 0D) {
        size += 1 + 8;
      }
      if (TimeStampRebut != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimeStampRebut);
      }
      if (TimeStampActual != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimeStampActual);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CalculDada other) {
      if (other == null) {
        return;
      }
      if (other.VariableCalcular.Length != 0) {
        VariableCalcular = other.VariableCalcular;
      }
      if (other.VariableRebuda.Length != 0) {
        VariableRebuda = other.VariableRebuda;
      }
      if (other.ValorRebut != 0D) {
        ValorRebut = other.ValorRebut;
      }
      if (other.TimeStampRebut != 0) {
        TimeStampRebut = other.TimeStampRebut;
      }
      if (other.TimeStampActual != 0) {
        TimeStampActual = other.TimeStampActual;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VariableCalcular = input.ReadString();
            break;
          }
          case 18: {
            VariableRebuda = input.ReadString();
            break;
          }
          case 25: {
            ValorRebut = input.ReadDouble();
            break;
          }
          case 32: {
            TimeStampRebut = input.ReadUInt32();
            break;
          }
          case 40: {
            TimeStampActual = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            VariableCalcular = input.ReadString();
            break;
          }
          case 18: {
            VariableRebuda = input.ReadString();
            break;
          }
          case 25: {
            ValorRebut = input.ReadDouble();
            break;
          }
          case 32: {
            TimeStampRebut = input.ReadUInt32();
            break;
          }
          case 40: {
            TimeStampActual = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Dada : pb::IMessage<Dada>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Dada> _parser = new pb::MessageParser<Dada>(() => new Dada());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Dada> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dada() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dada(Dada other) : this() {
      valor_ = other.valor_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dada Clone() {
      return new Dada(this);
    }

    /// <summary>Field number for the "valor" field.</summary>
    public const int ValorFieldNumber = 1;
    private double valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Dada);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Dada other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Valor, other.Valor)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Valor != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Valor);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Valor != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Valor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Valor != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Valor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Valor != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Dada other) {
      if (other == null) {
        return;
      }
      if (other.Valor != 0D) {
        Valor = other.Valor;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Valor = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Valor = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DatesConsulta : pb::IMessage<DatesConsulta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DatesConsulta> _parser = new pb::MessageParser<DatesConsulta>(() => new DatesConsulta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DatesConsulta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatesConsulta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatesConsulta(DatesConsulta other) : this() {
      dataInici_ = other.dataInici_ != null ? other.dataInici_.Clone() : null;
      dataFi_ = other.dataFi_ != null ? other.dataFi_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatesConsulta Clone() {
      return new DatesConsulta(this);
    }

    /// <summary>Field number for the "dataInici" field.</summary>
    public const int DataIniciFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dataInici_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DataInici {
      get { return dataInici_; }
      set {
        dataInici_ = value;
      }
    }

    /// <summary>Field number for the "dataFi" field.</summary>
    public const int DataFiFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dataFi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DataFi {
      get { return dataFi_; }
      set {
        dataFi_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DatesConsulta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DatesConsulta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(DataInici, other.DataInici)) return false;
      if (!object.Equals(DataFi, other.DataFi)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (dataInici_ != null) hash ^= DataInici.GetHashCode();
      if (dataFi_ != null) hash ^= DataFi.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (dataInici_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DataInici);
      }
      if (dataFi_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DataFi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (dataInici_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DataInici);
      }
      if (dataFi_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DataFi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (dataInici_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataInici);
      }
      if (dataFi_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataFi);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DatesConsulta other) {
      if (other == null) {
        return;
      }
      if (other.dataInici_ != null) {
        if (dataInici_ == null) {
          DataInici = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DataInici.MergeFrom(other.DataInici);
      }
      if (other.dataFi_ != null) {
        if (dataFi_ == null) {
          DataFi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DataFi.MergeFrom(other.DataFi);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (dataInici_ == null) {
              DataInici = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataInici);
            break;
          }
          case 18: {
            if (dataFi_ == null) {
              DataFi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataFi);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (dataInici_ == null) {
              DataInici = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataInici);
            break;
          }
          case 18: {
            if (dataFi_ == null) {
              DataFi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataFi);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RespostaDades : pb::IMessage<RespostaDades>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespostaDades> _parser = new pb::MessageParser<RespostaDades>(() => new RespostaDades());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespostaDades> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFG.Protobuf.MissatgesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespostaDades() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespostaDades(RespostaDades other) : this() {
      dades_ = other.dades_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespostaDades Clone() {
      return new RespostaDades(this);
    }

    /// <summary>Field number for the "Dades" field.</summary>
    public const int DadesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::TFG.Protobuf.Dada> _repeated_dades_codec
        = pb::FieldCodec.ForMessage(10, global::TFG.Protobuf.Dada.Parser);
    private readonly pbc::RepeatedField<global::TFG.Protobuf.Dada> dades_ = new pbc::RepeatedField<global::TFG.Protobuf.Dada>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TFG.Protobuf.Dada> Dades {
      get { return dades_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespostaDades);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespostaDades other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dades_.Equals(other.dades_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dades_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dades_.WriteTo(output, _repeated_dades_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dades_.WriteTo(ref output, _repeated_dades_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += dades_.CalculateSize(_repeated_dades_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespostaDades other) {
      if (other == null) {
        return;
      }
      dades_.Add(other.dades_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dades_.AddEntriesFrom(input, _repeated_dades_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dades_.AddEntriesFrom(ref input, _repeated_dades_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
